### ISSUE TITLE
GLFW error when rendering multiple components from list of data

### ISSUE THREAD

**Issue by vacarsu** [boydm/scenic#194]
OS:

```text
Linux
```

### Steps to reproduce

Render many components from an array of data.
E.G 
``` elixir
defp render_units(graph, units) do
    units
    |> Enum.with_index()
    |> Enum.reduce(graph, fn {unit, index}, graph ->
        graph
        |> render_unit(unit, index)
      end)
  end
```
### Expected Behavior

Scenic should render all the components with no errors regardless of how many.

### Actual Behavior

After about 25 items in the list :glwf threw this error
```
22:17:05.529 [error] GenServer :glfw terminating
** (MatchError) no match of right hand side value: {:error, :no_dl_id_free}
    (scenic_driver_glfw 0.10.1) lib/glfw/graph.ex:290: Scenic.Driver.Glfw.Graph.ensure_one_id/2
    (scenic_driver_glfw 0.10.1) lib/glfw/graph.ex:274: Scenic.Driver.Glfw.Graph.ensure_ids/2
    (stdlib 3.13) maps.erl:233: :maps.fold_1/3
    (scenic_driver_glfw 0.10.1) lib/glfw/graph.ex:244: anonymous fn/2 in Scenic.Driver.Glfw.Graph.render_graphs/3
    (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (scenic_driver_glfw 0.10.1) lib/glfw/graph.ex:243: Scenic.Driver.Glfw.Graph.render_graphs/3
    (scenic_driver_glfw 0.10.1) lib/glfw/graph.ex:274: Scenic.Driver.Glfw.Graph.ensure_ids/2
    (stdlib 3.13) maps.erl:233: :maps.fold_1/3
```

**Comment by boydm** [comment]
This is because you have so many components that you have exhausted the supply of draw list ids. You can increase the supply by setting the (just a sec, I have to look this up...)  `:block_size` option to a higher number. The default 512. Try 1000. You can see the other options in the glfx.ex file in scenic_driver_glfw.

To give some more context.

When you update a scene, that graph is turned into a render script, which is handed down to the actual port that does the rendering. The scene is assigned an id, which is really just a slot in a fixed size table of pointers in the render port. When it runs out of slots, you get the error above.

The motivation of doing this is so that the minimal amount of work can be done rendering scripts and images. The unchanged scripts are kept cached in the port and only the changed one is sent down. When you nest scenes, you are effectively calling a cached script from within your script.

In the future I may get rid of the fixed size array and go with some sort of hashmap in the C port. This would remove the fixed array limit. Things would still fail when there are too many scenes, but then the limit would be when it runs out of memory instead of slots.

**Comment by vacarsu** [comment]
Thanks for the info, is `:block_size` set in the viewport config?

**Comment by vacarsu** [comment]
What is a sensible number for this? I set it to 10000 and it works wonderfully. It is hard to know how many components I will be rendering and any given time. I'm creating a sequence runner that will send commands to a network of devices via CAN bus that will orchestrate devices to accomplish various micro fluidics tasks. There could be hundres of units (which are just commands that will run at a given point in time.).

**Comment by boydm** [comment]
1) I totally want to hear about what you are working on. You just totally got my attention.
2) I'd pick some factor of safety (4?) and multiply the largest number you realistically expect and go with that.
3) Supporting what you are talking about is very interesting. If needed we can talk about switching out the it for the hashmap. Not work I want to do until really needed though.

**Comment by vacarsu** [comment]
Thanks @boydm, I've spoken with a coworker and he said the most units well have in a sequence would be 2000, so I would need a block size of around 8000 - 10,000. Not sure at which point a hashmap would be better. I would love to give more details about the project, over email perhaps?

**Comment by vacarsu** [comment]
@boydm What would be the best way to ensure drop downs render above other components? For example if I'm rendering a units from a list of data, and those components each have a drop down rendered inside of them. With the current array based rendering the most recent item is rendered above previously rendered components.
